create model based on pre-trained VGG16 (WIP)
Szuumii/GSNCars pull request #1
Opened 2021-12-07 20:22 UTC by Temebe

2021-12-07 21:42 UTC, Szuumii commented on .gitignore
> +settings.json
Why .json file ?! O.o

2021-12-07 22:19 UTC, Szuumii requested changes

2021-12-07 22:19 UTC, Szuumii commented on models.py
> +        self.loss = nn.NLLLoss()
We should go for cross-entropy loss: https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html

2021-12-07 22:19 UTC, Szuumii commented on models.py
> +        x, _ = batch
We like to read prod_year instead of _

2021-12-07 22:22 UTC, Temebe commented on models.py
> +        self.net.classifier[6] = nn.Linear(last_in_features, 19)
That is actually ` Prod_year_max - prod_year_min` :) Just hidden behind magic number. I will clarify this in code.

2021-12-07 22:30 UTC, Szuumii commented on models.py
> +        self.net.classifier[6] = nn.Linear(last_in_features, 19)
Magic numbers are never a good idea :D We should also consider number of classes that are in the main data folder, since they might not be included in this subset of confirmed

2021-12-09 00:32 UTC, Temebe commented on models.py
> +    def __init__(self, dataset_csv_path, dataset_dir_path, batch_size=32):
I've added small_train flag to model constructor. It picks randomly 5% of original dataset. Let me know if that is sufficient or if we want to go with specifically prepared sets.

2021-12-09 00:37 UTC, Temebe commented on models.py
> +        PROD_YEAR_RANGE = self.dataset.maximum_prod_year() - self.dataset.minimum_prod_year() + 1
This right here is something I am not really comfortable with :)
I get minimum and maximum years of production from csv files, which are processed by FrontDataset class. However, it is needed when we create network, as we are changing outputs of last layer based on these years. I moved creating dataset object in `__init__` function from `prepare_data`, but I am not entirely sure if it is ok.

2021-12-09 00:38 UTC, Temebe commented on models.py
> +        return self.training_step(batch, batch_idx)
Do we want to create separate folders for validation? Or will we just take some subset of original dataset (randomly or simply by taking last few percentages)?

2021-12-09 00:42 UTC, Temebe commented on dataset/CarFronts.py
> +        self.data = self.data[np.random.choice(self.data.shape[0], size, replace=False), :]
I came up with this as a way to pick subset of data with flag small_train. Let me know if you have some comments, if it is not readable or if I should simply get rid of this.

2021-12-09 21:06 UTC, Szuumii requested changes

2021-12-09 21:06 UTC, Szuumii commented on models.py
> +        return self.training_step(batch, batch_idx)
We could split original csv into test, data, and validation up front. In this case data preparation could be a little more transparent. I'll look for an example and give you feedback later on ;)

2021-12-11 15:35 UTC, Temebe commented on models.py
> +        PROD_YEAR_RANGE = FrontDataset.prod_years_range(csv_path)
I came up with static method in FrontDataset, which calculates this range. I was hesitant to putting logic of operating on this csv file in Model class. I am not sure however if we want to keep it as static method. Let me know :)

2021-12-11 19:00 UTC, Szuumii commented on models.py
> +        PROD_YEAR_RANGE = FrontDataset.prod_years_range(csv_path)
This solution looks great! 👍  However, I still we should ask about it during the consultation

2021-12-15 19:25 UTC, Szuumii approved these changes

2021-12-15 19:25 UTC, Szuumii commented on models.py
> +        SMALL_DATA_PERCENTAGE = 0.01
This is correct, however, I think that instead of such a huge chunk of code that creates those sets out random, I'd just give paths to preprocessed CSV files that are split out random. I'll correct it

2021-12-15 20:48 UTC, Temebe commented on model/models.py
> +        loss = self.loss(predictions, (prod_year - self.train_dataset.minimum_prod_year()))
Maybe we should set minimum prod year as separate variable in prepare_data method? Using train_dataset in validation_step might be confusing. 

It could be also just predefined like PROD_YEAR_RANGE

2021-12-15 21:05 UTC, merged